[package]
authors = ["Jeremy <jere.arde@gmail.com>"]
edition = "2018"
name = "advent_of_code_2020"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
